version: '3.8'

services:
  frontend:
    image: ghcr.io/modsetter/surfsense_ui:latest
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./surfsense_web:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:8000}

  backend:
    image: ghcr.io/modsetter/surfsense_backend:latest
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./surfsense_backend:/app
      - hf_cache:/cache # Add named volume mount for HF cache
    depends_on:
      - db
    env_file:
      - ./surfsense_backend/.env
    environment:
      - AUTH_TYPE=${AUTH_TYPE:-LOCAL}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-surfsense}
      - PYTHONPATH=/app
      - UVICORN_LOOP=asyncio
      - UNSTRUCTURED_HAS_PATCHED_LOOP=1
      # Add these for local HF cache persistence
      - HF_HOME=/cache/huggingface
      - TOKENIZERS_PARALLELISM=false
      # Remove these if they exist from previous configurations
      # - HF_HOME=/app/.cache/huggingface
      # - TRANSFORMERS_CACHE=/app/.cache/transformers

volumes:
  postgres_data: # This might already exist from docker-compose.yml
  pgadmin_data:  # This might already exist from docker-compose.yml
  hf_cache: {}   # Define the named volume for Hugging Face cache